name: Build/Test/Deploy
on: [push]

jobs:
  ci:
    name: ci
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: cache
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: install
        id: install
        run: npm ci
        if: steps.cache.outputs.cache-hit != true
      - name: lint
        id: lint
        run: npm run lint
      - name: test
        id: test
        run: npm run test
      - name: build
        id: build
        run: npm run build
      - name: deploy
        id: deploy
        if: github.ref == 'refs/heads/troubleshoot'
        uses: carlegbert/github-actions-rsync@master
        with:
          rsync-target: ${{ secrets.DEST_DIR }}
          rsynt-source: dist/
        env:
          RSYNC_OPTIONS: -avzr --delete
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          SSH_USERNAME: ${{ secrets.SSH_USER }}
          SSH_HOSTNAME: ${{ secrets.HOST }}
          RSYNC_PASSWORD: ${{ secrets.SSH_PASSWD }}
